from collections import deque


def triangle(numRow: int):
    res = []
    for i in range(1, numRow + 1):
        res.append([1 for _ in range(i)])
        if i > 2:
            for j in range(1, i - 1):
                res[i - 1][j] = res[i - 2][j - 1] + res[i - 2][j]

    return res


class World:
    def words_in_box(self, board, words):
        if not board or not words:
            return []

        self.board = board
        self.y = len(board)
        self.x = len(board[0])
        x = []
        for a in board:
            x += list(set(a))
        s = "".join(list(set(x)))

        res = []
        for word in set(words):
            if any([True for x in word if x not in s]):
                continue

            if word not in res and self.check_in(word):
                res.append(word)

        return res

    def check_in(self, word):
        len_w = len(word) - 1
        for y in range(self.y):
            for x in range(self.x):
                if (
                    self.board[y][x] == word[0]
                    and self.check_word(word, 0, x, y, deque(), len_w)[0]
                ):
                    return True

    def check_word(self, word, litera_id=0, x=0, y=0, path=deque(), len_w=0):
        success = False

        if word[litera_id] == self.board[y][x] and (x, y) not in path:
            if litera_id == len_w:
                return True, None

            path.append((x, y))

            if x - 1 >= 0:
                success, path = self.check_word(
                    word, litera_id + 1, x - 1, y, path, len_w
                )
            if not success and x + 1 < self.x:
                success, path = self.check_word(
                    word, litera_id + 1, x + 1, y, path, len_w
                )
            if not success and y - 1 >= 0:
                success, path = self.check_word(
                    word, litera_id + 1, x, y - 1, path, len_w
                )
            if not success and y + 1 < self.y:
                success, path = self.check_word(
                    word, litera_id + 1, x, y + 1, path, len_w
                )
            if not success:
                path.pop()
        return success, path


def max_income(prices):
    if not prices or len(prices) <= 1:
        return 0
    n = [prices[0]]
    for i in range(1, len(prices)):
        if prices[i] != prices[i - 1]:
            n.append(prices[i])
    m = 0
    for i in range(len(n)):
        m = max(list(map(lambda x: x - n[i], n[i:])) + [m])
    return m


def test_max_income():
    assert max_income([7, 1, 5, 3, 6, 4]) == 5
    assert max_income([2, 1, 2, 0, 1]) == 1
    assert max_income([1, 2]) == 1


def test_words_in_box():
    ins = World()
    assert ins.words_in_box([["a"]], ["a"]) == ["a"]

    assert (
        sorted(
            ins.words_in_box(
                [
                    ["o", "a", "a", "n"],
                    ["e", "t", "a", "e"],
                    ["i", "h", "k", "r"],
                    ["i", "f", "l", "v"],
                ],
                ["oath", "eat", "rain"],
            )
        )
        == sorted(["eat", "oath"])
    )


def test_fooooooh():
    ins = World()
    assert (
        sorted(
            ins.words_in_box(
                [
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                    ["b", "a", "b", "a", "b", "a", "b", "a", "b", "a"],
                    ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b"],
                ],
                [
                    "ababababaa",
                    "ababababab",
                    "ababababac",
                    "ababababad",
                    "ababababae",
                    "ababababaf",
                    "ababababag",
                    "ababababah",
                    "ababababai",
                    "ababababaj",
                    "ababababak",
                    "ababababal",
                    "ababababam",
                    "ababababan",
                    "ababababao",
                    "ababababap",
                    "ababababaq",
                    "ababababar",
                    "ababababas",
                    "ababababat",
                    "ababababau",
                    "ababababav",
                    "ababababaw",
                    "ababababax",
                    "ababababay",
                    "ababababaz",
                    "ababababba",
                    "ababababbb",
                    "ababababbc",
                    "ababababbd",
                    "ababababbe",
                    "ababababbf",
                    "ababababbg",
                    "ababababbh",
                    "ababababbi",
                    "ababababbj",
                    "ababababbk",
                    "ababababbl",
                    "ababababbm",
                    "ababababbn",
                    "ababababbo",
                    "ababababbp",
                    "ababababbq",
                    "ababababbr",
                    "ababababbs",
                    "ababababbt",
                    "ababababbu",
                    "ababababbv",
                    "ababababbw",
                    "ababababbx",
                    "ababababby",
                    "ababababbz",
                    "ababababca",
                    "ababababcb",
                    "ababababcc",
                    "ababababcd",
                    "ababababce",
                    "ababababcf",
                    "ababababcg",
                    "ababababch",
                    "ababababci",
                    "ababababcj",
                    "ababababck",
                    "ababababcl",
                    "ababababcm",
                    "ababababcn",
                    "ababababco",
                    "ababababcp",
                    "ababababcq",
                    "ababababcr",
                    "ababababcs",
                    "ababababct",
                    "ababababcu",
                    "ababababcv",
                    "ababababcw",
                    "ababababcx",
                    "ababababcy",
                    "ababababcz",
                    "ababababda",
                    "ababababdb",
                    "ababababdc",
                    "ababababdd",
                    "ababababde",
                    "ababababdf",
                    "ababababdg",
                    "ababababdh",
                    "ababababdi",
                    "ababababdj",
                    "ababababdk",
                    "ababababdl",
                    "ababababdm",
                    "ababababdn",
                    "ababababdo",
                    "ababababdp",
                    "ababababdq",
                    "ababababdr",
                    "ababababds",
                    "ababababdt",
                    "ababababdu",
                    "ababababdv",
                    "ababababdw",
                    "ababababdx",
                    "ababababdy",
                    "ababababdz",
                    "ababababea",
                    "ababababeb",
                    "ababababec",
                    "ababababed",
                    "ababababee",
                    "ababababef",
                    "ababababeg",
                    "ababababeh",
                    "ababababei",
                    "ababababej",
                    "ababababek",
                    "ababababel",
                    "ababababem",
                    "ababababen",
                    "ababababeo",
                    "ababababep",
                    "ababababeq",
                    "ababababer",
                    "ababababes",
                    "ababababet",
                    "ababababeu",
                    "ababababev",
                    "ababababew",
                    "ababababex",
                    "ababababey",
                    "ababababez",
                    "ababababfa",
                    "ababababfb",
                    "ababababfc",
                    "ababababfd",
                    "ababababfe",
                    "ababababff",
                    "ababababfg",
                    "ababababfh",
                    "ababababfi",
                    "ababababfj",
                    "ababababfk",
                    "ababababfl",
                    "ababababfm",
                    "ababababfn",
                    "ababababfo",
                    "ababababfp",
                    "ababababfq",
                    "ababababfr",
                    "ababababfs",
                    "ababababft",
                    "ababababfu",
                    "ababababfv",
                    "ababababfw",
                    "ababababfx",
                    "ababababfy",
                    "ababababfz",
                    "ababababga",
                    "ababababgb",
                    "ababababgc",
                    "ababababgd",
                    "ababababge",
                    "ababababgf",
                    "ababababgg",
                    "ababababgh",
                    "ababababgi",
                    "ababababgj",
                    "ababababgk",
                    "ababababgl",
                    "ababababgm",
                    "ababababgn",
                    "ababababgo",
                    "ababababgp",
                    "ababababgq",
                    "ababababgr",
                    "ababababgs",
                    "ababababgt",
                    "ababababgu",
                    "ababababgv",
                    "ababababgw",
                    "ababababgx",
                    "ababababgy",
                    "ababababgz",
                    "ababababha",
                    "ababababhb",
                    "ababababhc",
                    "ababababhd",
                    "ababababhe",
                    "ababababhf",
                    "ababababhg",
                    "ababababhh",
                    "ababababhi",
                    "ababababhj",
                    "ababababhk",
                    "ababababhl",
                    "ababababhm",
                    "ababababhn",
                    "ababababho",
                    "ababababhp",
                    "ababababhq",
                    "ababababhr",
                    "ababababhs",
                    "ababababht",
                    "ababababhu",
                    "ababababhv",
                    "ababababhw",
                    "ababababhx",
                    "ababababhy",
                    "ababababhz",
                    "ababababia",
                    "ababababib",
                    "ababababic",
                    "ababababid",
                    "ababababie",
                    "ababababif",
                    "ababababig",
                    "ababababih",
                    "ababababii",
                    "ababababij",
                    "ababababik",
                    "ababababil",
                    "ababababim",
                    "ababababin",
                    "ababababio",
                    "ababababip",
                    "ababababiq",
                    "ababababir",
                    "ababababis",
                    "ababababit",
                    "ababababiu",
                    "ababababiv",
                    "ababababiw",
                    "ababababix",
                    "ababababiy",
                    "ababababiz",
                    "ababababja",
                    "ababababjb",
                    "ababababjc",
                    "ababababjd",
                    "ababababje",
                    "ababababjf",
                    "ababababjg",
                    "ababababjh",
                    "ababababji",
                    "ababababjj",
                    "ababababjk",
                    "ababababjl",
                    "ababababjm",
                    "ababababjn",
                    "ababababjo",
                    "ababababjp",
                    "ababababjq",
                    "ababababjr",
                    "ababababjs",
                    "ababababjt",
                    "ababababju",
                    "ababababjv",
                    "ababababjw",
                    "ababababjx",
                    "ababababjy",
                    "ababababjz",
                    "ababababka",
                    "ababababkb",
                    "ababababkc",
                    "ababababkd",
                    "ababababke",
                    "ababababkf",
                    "ababababkg",
                    "ababababkh",
                    "ababababki",
                    "ababababkj",
                    "ababababkk",
                    "ababababkl",
                    "ababababkm",
                    "ababababkn",
                    "ababababko",
                    "ababababkp",
                    "ababababkq",
                    "ababababkr",
                    "ababababks",
                    "ababababkt",
                    "ababababku",
                    "ababababkv",
                    "ababababkw",
                    "ababababkx",
                    "ababababky",
                    "ababababkz",
                    "ababababla",
                    "abababablb",
                    "abababablc",
                    "ababababld",
                    "abababable",
                    "abababablf",
                    "abababablg",
                    "abababablh",
                    "ababababli",
                    "abababablj",
                    "abababablk",
                    "ababababll",
                    "abababablm",
                    "ababababln",
                    "abababablo",
                    "abababablp",
                    "abababablq",
                    "abababablr",
                    "ababababls",
                    "abababablt",
                    "abababablu",
                    "abababablv",
                    "abababablw",
                    "abababablx",
                    "abababably",
                    "abababablz",
                    "ababababma",
                    "ababababmb",
                    "ababababmc",
                    "ababababmd",
                    "ababababme",
                    "ababababmf",
                    "ababababmg",
                    "ababababmh",
                    "ababababmi",
                    "ababababmj",
                    "ababababmk",
                    "ababababml",
                    "ababababmm",
                    "ababababmn",
                    "ababababmo",
                    "ababababmp",
                    "ababababmq",
                    "ababababmr",
                    "ababababms",
                    "ababababmt",
                    "ababababmu",
                    "ababababmv",
                    "ababababmw",
                    "ababababmx",
                    "ababababmy",
                    "ababababmz",
                    "ababababna",
                    "ababababnb",
                    "ababababnc",
                    "ababababnd",
                    "ababababne",
                    "ababababnf",
                    "ababababng",
                    "ababababnh",
                    "ababababni",
                    "ababababnj",
                    "ababababnk",
                    "ababababnl",
                    "ababababnm",
                    "ababababnn",
                    "ababababno",
                    "ababababnp",
                    "ababababnq",
                    "ababababnr",
                    "ababababns",
                    "ababababnt",
                    "ababababnu",
                    "ababababnv",
                    "ababababnw",
                    "ababababnx",
                    "ababababny",
                    "ababababnz",
                    "ababababoa",
                    "ababababob",
                    "ababababoc",
                    "ababababod",
                    "ababababoe",
                    "ababababof",
                    "ababababog",
                    "ababababoh",
                    "ababababoi",
                    "ababababoj",
                    "ababababok",
                    "ababababol",
                    "ababababom",
                    "ababababon",
                    "ababababoo",
                    "ababababop",
                    "ababababoq",
                    "ababababor",
                    "ababababos",
                    "ababababot",
                    "ababababou",
                    "ababababov",
                    "ababababow",
                    "ababababox",
                    "ababababoy",
                    "ababababoz",
                    "ababababpa",
                    "ababababpb",
                    "ababababpc",
                    "ababababpd",
                    "ababababpe",
                    "ababababpf",
                    "ababababpg",
                    "ababababph",
                    "ababababpi",
                    "ababababpj",
                    "ababababpk",
                    "ababababpl",
                    "ababababpm",
                    "ababababpn",
                    "ababababpo",
                    "ababababpp",
                    "ababababpq",
                    "ababababpr",
                    "ababababps",
                    "ababababpt",
                    "ababababpu",
                    "ababababpv",
                    "ababababpw",
                    "ababababpx",
                    "ababababpy",
                    "ababababpz",
                    "ababababqa",
                    "ababababqb",
                    "ababababqc",
                    "ababababqd",
                    "ababababqe",
                    "ababababqf",
                    "ababababqg",
                    "ababababqh",
                    "ababababqi",
                    "ababababqj",
                    "ababababqk",
                    "ababababql",
                    "ababababqm",
                    "ababababqn",
                    "ababababqo",
                    "ababababqp",
                    "ababababqq",
                    "ababababqr",
                    "ababababqs",
                    "ababababqt",
                    "ababababqu",
                    "ababababqv",
                    "ababababqw",
                    "ababababqx",
                    "ababababqy",
                    "ababababqz",
                    "ababababra",
                    "ababababrb",
                    "ababababrc",
                    "ababababrd",
                    "ababababre",
                    "ababababrf",
                    "ababababrg",
                    "ababababrh",
                    "ababababri",
                    "ababababrj",
                    "ababababrk",
                    "ababababrl",
                    "ababababrm",
                    "ababababrn",
                    "ababababro",
                    "ababababrp",
                    "ababababrq",
                    "ababababrr",
                    "ababababrs",
                    "ababababrt",
                    "ababababru",
                    "ababababrv",
                    "ababababrw",
                    "ababababrx",
                    "ababababry",
                    "ababababrz",
                    "ababababsa",
                    "ababababsb",
                    "ababababsc",
                    "ababababsd",
                    "ababababse",
                    "ababababsf",
                    "ababababsg",
                    "ababababsh",
                    "ababababsi",
                    "ababababsj",
                    "ababababsk",
                    "ababababsl",
                    "ababababsm",
                    "ababababsn",
                    "ababababso",
                    "ababababsp",
                    "ababababsq",
                    "ababababsr",
                    "ababababss",
                    "ababababst",
                    "ababababsu",
                    "ababababsv",
                    "ababababsw",
                    "ababababsx",
                    "ababababsy",
                    "ababababsz",
                    "ababababta",
                    "ababababtb",
                    "ababababtc",
                    "ababababtd",
                    "ababababte",
                    "ababababtf",
                    "ababababtg",
                    "ababababth",
                    "ababababti",
                    "ababababtj",
                    "ababababtk",
                    "ababababtl",
                    "ababababtm",
                    "ababababtn",
                    "ababababto",
                    "ababababtp",
                    "ababababtq",
                    "ababababtr",
                    "ababababts",
                    "ababababtt",
                    "ababababtu",
                    "ababababtv",
                    "ababababtw",
                    "ababababtx",
                    "ababababty",
                    "ababababtz",
                    "ababababua",
                    "ababababub",
                    "ababababuc",
                    "ababababud",
                    "ababababue",
                    "ababababuf",
                    "ababababug",
                    "ababababuh",
                    "ababababui",
                    "ababababuj",
                    "ababababuk",
                    "ababababul",
                    "ababababum",
                    "ababababun",
                    "ababababuo",
                    "ababababup",
                    "ababababuq",
                    "ababababur",
                    "ababababus",
                    "ababababut",
                    "ababababuu",
                    "ababababuv",
                    "ababababuw",
                    "ababababux",
                    "ababababuy",
                    "ababababuz",
                    "ababababva",
                    "ababababvb",
                    "ababababvc",
                    "ababababvd",
                    "ababababve",
                    "ababababvf",
                    "ababababvg",
                    "ababababvh",
                    "ababababvi",
                    "ababababvj",
                    "ababababvk",
                    "ababababvl",
                    "ababababvm",
                    "ababababvn",
                    "ababababvo",
                    "ababababvp",
                    "ababababvq",
                    "ababababvr",
                    "ababababvs",
                    "ababababvt",
                    "ababababvu",
                    "ababababvv",
                    "ababababvw",
                    "ababababvx",
                    "ababababvy",
                    "ababababvz",
                    "ababababwa",
                    "ababababwb",
                    "ababababwc",
                    "ababababwd",
                    "ababababwe",
                    "ababababwf",
                    "ababababwg",
                    "ababababwh",
                    "ababababwi",
                    "ababababwj",
                    "ababababwk",
                    "ababababwl",
                    "ababababwm",
                    "ababababwn",
                    "ababababwo",
                    "ababababwp",
                    "ababababwq",
                    "ababababwr",
                    "ababababws",
                    "ababababwt",
                    "ababababwu",
                    "ababababwv",
                    "ababababww",
                    "ababababwx",
                    "ababababwy",
                    "ababababwz",
                    "ababababxa",
                    "ababababxb",
                    "ababababxc",
                    "ababababxd",
                    "ababababxe",
                    "ababababxf",
                    "ababababxg",
                    "ababababxh",
                    "ababababxi",
                    "ababababxj",
                    "ababababxk",
                    "ababababxl",
                    "ababababxm",
                    "ababababxn",
                    "ababababxo",
                    "ababababxp",
                    "ababababxq",
                    "ababababxr",
                    "ababababxs",
                    "ababababxt",
                    "ababababxu",
                    "ababababxv",
                    "ababababxw",
                    "ababababxx",
                    "ababababxy",
                    "ababababxz",
                    "ababababya",
                    "ababababyb",
                    "ababababyc",
                    "ababababyd",
                    "ababababye",
                    "ababababyf",
                    "ababababyg",
                    "ababababyh",
                    "ababababyi",
                    "ababababyj",
                    "ababababyk",
                    "ababababyl",
                    "ababababym",
                    "ababababyn",
                    "ababababyo",
                    "ababababyp",
                    "ababababyq",
                    "ababababyr",
                    "ababababys",
                    "ababababyt",
                    "ababababyu",
                    "ababababyv",
                    "ababababyw",
                    "ababababyx",
                    "ababababyy",
                    "ababababyz",
                    "ababababza",
                    "ababababzb",
                    "ababababzc",
                    "ababababzd",
                    "ababababze",
                    "ababababzf",
                    "ababababzg",
                    "ababababzh",
                    "ababababzi",
                    "ababababzj",
                    "ababababzk",
                    "ababababzl",
                    "ababababzm",
                    "ababababzn",
                    "ababababzo",
                    "ababababzp",
                    "ababababzq",
                    "ababababzr",
                    "ababababzs",
                    "ababababzt",
                    "ababababzu",
                    "ababababzv",
                    "ababababzw",
                    "ababababzx",
                    "ababababzy",
                    "ababababzz",
                ],
            )
        )
        == ["ababababab"]
    )

    assert (
        sorted(
            ins.words_in_box(
                [
                    ["o", "a", "a", "n"],
                    ["e", "t", "a", "e"],
                    ["i", "h", "k", "r"],
                    ["i", "f", "l", "v"],
                ],
                ["rain"],
            )
        )
        == sorted([])
    )


def test_triangle():
    assert triangle(1) == [[1]]
    assert triangle(3) == [[1], [1, 1], [1, 2, 1]]
    assert triangle(4) == [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1]]


if __name__ == "__main__":
    """
    for cProfile
    """
    test_foo()
